// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/presentation/migrate_to_bloc/bloc_migrate_movie_and_tvls/migrate_tvls_on_air_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i5;
import 'package:ditonton/common/failure.dart' as _i8;
import 'package:ditonton/domain/entities/tvls/tvls.dart' as _i9;
import 'package:ditonton/domain/repositories/tvls_repository.dart' as _i4;
import 'package:ditonton/domain/usecases/tvls/get_now_playing_tvls.dart' as _i2;
import 'package:ditonton/presentation/migrate_to_bloc/bloc_migrate_tvls/bloc_migrate_on_air_tvls/migrate_tvls_on_air_bloc.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetNowPlayingTvls_0 extends _i1.Fake
    implements _i2.GetNowPlayingTvls {}

class _FakeMigrateTvlsOnAirState_1 extends _i1.Fake
    implements _i3.MigrateTvlsOnAirState {}

class _FakeTvlsRepository_2 extends _i1.Fake implements _i4.TvlsRepository {}

class _FakeEither_3<L, R> extends _i1.Fake implements _i5.Either<L, R> {}

/// A class which mocks [MigrateTvlsOnAirBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMigrateTvlsOnAirBloc extends _i1.Mock
    implements _i3.MigrateTvlsOnAirBloc {
  MockMigrateTvlsOnAirBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetNowPlayingTvls get getMigrateOnAirTvls =>
      (super.noSuchMethod(Invocation.getter(#getMigrateOnAirTvls),
          returnValue: _FakeGetNowPlayingTvls_0()) as _i2.GetNowPlayingTvls);
  @override
  _i3.MigrateTvlsOnAirState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeMigrateTvlsOnAirState_1())
          as _i3.MigrateTvlsOnAirState);
  @override
  _i6.Stream<_i3.MigrateTvlsOnAirState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.MigrateTvlsOnAirState>.empty())
          as _i6.Stream<_i3.MigrateTvlsOnAirState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.MigrateTvlsOnAirEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.MigrateTvlsOnAirEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i3.MigrateTvlsOnAirState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.MigrateTvlsOnAirEvent>(
          _i7.EventHandler<E, _i3.MigrateTvlsOnAirState>? handler,
          {_i7.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i7.Transition<_i3.MigrateTvlsOnAirEvent, _i3.MigrateTvlsOnAirState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void onChange(_i7.Change<_i3.MigrateTvlsOnAirState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetNowPlayingTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingTvls extends _i1.Mock implements _i2.GetNowPlayingTvls {
  MockGetNowPlayingTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_2()) as _i4.TvlsRepository);
  @override
  _i6.Future<_i5.Either<_i8.Failure, List<_i9.Tvls>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i5.Either<_i8.Failure, List<_i9.Tvls>>>.value(
              _FakeEither_3<_i8.Failure, List<_i9.Tvls>>())) as _i6
          .Future<_i5.Either<_i8.Failure, List<_i9.Tvls>>>);
}
